# camera parameters <== Path(CONFIG.camera.folder) / f'{camera_id}_calibration.yaml'
camera:
  folder: ../../conf/camera
  cam_ids:
    - '22276213'
    - '22276209'
    - '22276216'
  image_dim: [1280, 1080]

# dataset for training
dataset:
  folder: ../../data/synthetic
  camera_data: synthetic_camera_data.csv
  trajectory_data: synthetic_traj_data.csv


# syntheic settings
synthetic:
  total_traj_num: 500
  p0: [0.5, -2.4, 0.4] # m
  dp0: [0.1, 0.1, 0.1]
  v0:  [0.0, 3.0, 1.5] # m/s
  dv0: [0.5, 1.0, 1.0] 
  w0:  [10.0, 0.0, 0.0] # hz
  dw0: [10, 30, 10]
  uv_noise: 3 # px
  t_max: 1.0 # sec
  seq_len: 200


# training parameters
model_name: gru # gru, mamba_ssm, gated_mlp
seed: 42
num_epochs: 200
lr_init: 1e-1
lr_gamma: 1.3
lr_step_size: 10
training_data_split: 0.8
batch_trajectory: 20
estimation_fraction: 0.25

# model parameters
model:
  gru:
    input_size: 3
    hidden_size: 128
    num_layers: 2
    output_size: 3
    model_path: ../../data/model/syntheic_gru.pth
    logdir: ../../logdir/gru
  mamba_ssm:
